# Stage 1: Use yarn to build the app
# FROM artifacts.developer.gov.bc.ca/docker-remote/node:20 as builder
# WORKDIR /usr/src/app
# COPY ./ ./
# RUN npm install -g npm@9.1.1 \
#     && npm install --omit=dev \
#     && npm install -D webpack webpack-cli
# RUN yes | npm run dist
FROM artifacts.developer.gov.bc.ca/docker-remote/node:20.18.1 as builder
WORKDIR /usr/src/app
COPY ./ ./
# RUN npm install -g npm@latest    doesn't work for node 16
RUN npm install --force
RUN pwd && \
  ls -l && \
  ls -l node_modules
RUN yes | npm run build

# Stage 2: Copy the JS React SPA into the Nginx HTML directory
FROM artifacts.developer.gov.bc.ca/docker-remote/bitnami/nginx:1.24.0
COPY ./nginx.conf /opt/bitnami/nginx/conf/
COPY --from=builder /usr/src/app/build /app
RUN ls -l /app
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]

