# Stage 1: Use yarn to build the app
# FROM artifacts.developer.gov.bc.ca/docker-remote/node:20 as builder
# WORKDIR /usr/src/app
# COPY ./ ./
# RUN npm install -g npm@9.1.1 \
#     && npm install --omit=dev \
#     && npm install -D webpack webpack-cli
# RUN yes | npm run dist
FROM artifacts.developer.gov.bc.ca/docker-remote/node:20 as builder
ENV NODE_ENV=production
ENV NODE_PATH=/usr/local/lib/node_modules:/usr/src/app/node_modules
WORKDIR /usr/src/app
COPY ./ ./
RUN npm install -g npm@latest
RUN npm install --omit=dev
RUN yes | npm install -g webpack webpack-cli copy-webpack-plugin
RUN echo $NODE_PATH
RUN pwd && \
  ls -l && \
  ls -l node_modules && \
  ls -l /usr/local/lib/node_modules
RUN yes | npm run build
RUN pwd && \
    ls -l && \
    tree


# Stage 2: Copy the JS React SPA into the Nginx HTML directory
FROM artifacts.developer.gov.bc.ca/docker-remote/bitnami/nginx:1.24.0
COPY ./nginx.conf /opt/bitnami/nginx/conf/
COPY --from=builder /usr/src/app/public/build /app
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]

