# Generated by Django 3.1.6 on 2021-11-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LdvRebates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_timestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("create_user", models.CharField(default="SYSTEM", max_length=130)),
                ("update_timestamp", models.DateTimeField(auto_now=True, null=True)),
                ("update_user", models.CharField(max_length=130, null=True)),
                ("submission_id", models.IntegerField(unique=True)),
                ("casl_consent", models.BooleanField(default=False)),
                ("date_approved", models.DateField(blank=True, null=True)),
                ("submission_date", models.DateField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company_city",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "applicant_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "applicant_address_1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "applicant_address_2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "applicant_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "applicant_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "applicant_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "applicant_email",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "applicant_use",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "applicant_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "drivers_license",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("province", models.CharField(blank=True, max_length=50, null=True)),
                ("msrp", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "other_incentives",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("vehicle", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "incentive_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("vin", models.CharField(blank=True, max_length=255, null=True)),
                ("delivered", models.BooleanField(default=False)),
                ("consent_to_contact", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ldv_rebates",
            },
        ),
    ]
