# Generated by Django 3.1.6 on 2021-12-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_chargerrebates_fix_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargerrebates",
            name="expected_in_service_date",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
