# Generated by Django 3.1.6 on 2021-12-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20211216_1944"),
    ]

    operations = [
        migrations.CreateModel(
            name="HydrogrenFueling",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "create_timestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("create_user", models.CharField(default="SYSTEM", max_length=130)),
                ("update_timestamp", models.DateTimeField(auto_now=True, null=True)),
                ("update_user", models.CharField(max_length=130, null=True)),
                ("station_number", models.IntegerField(blank=True, null=True)),
                ("rfp_close_date", models.DateField(blank=True, null=True)),
                (
                    "station_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=50, null=True)),
                ("proponent", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location_partner",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "capital_funding_awarded",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "om_funding_potential",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("daily_capacity", models.IntegerField(blank=True, null=True)),
                ("bar_700", models.BooleanField(default=False)),
                ("bar_350", models.BooleanField(default=False)),
                ("status", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "number_of_fueling_positions",
                    models.IntegerField(blank=True, null=True),
                ),
                ("operational_date", models.DateField(blank=True, null=True)),
                ("opening_date", models.DateField(blank=True, null=True)),
                (
                    "total_capital_cost",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
            options={
                "db_table": "hydrogen_fueling",
            },
        ),
    ]
