# Generated by Django 3.1.6 on 2021-12-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_hydrogrenfueling"),
    ]

    operations = [
        migrations.CreateModel(
            name="HydrogenFleets",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_timestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("create_user", models.CharField(default="SYSTEM", max_length=130)),
                ("update_timestamp", models.DateTimeField(auto_now=True, null=True)),
                ("update_user", models.CharField(max_length=130, null=True)),
                ("application_number", models.IntegerField(blank=True, null=True)),
                ("fleet_number", models.IntegerField(blank=True, null=True)),
                (
                    "application_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("fleet_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "steet_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("vin", models.CharField(blank=True, max_length=20, null=True)),
                ("make", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "purchase_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dealer_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "rebate_amount",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "db_table": "hydrogen_fleets",
            },
        ),
    ]
