# Generated by Django 3.1.6 on 2022-01-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_arcprojecttracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapIt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_timestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("create_user", models.CharField(default="SYSTEM", max_length=130)),
                ("update_timestamp", models.DateTimeField(auto_now=True, null=True)),
                ("update_user", models.CharField(max_length=130, null=True)),
                ("approval_number", models.IntegerField(blank=True, null=True)),
                (
                    "application_received_date",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "completion_date",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("vin", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "application_city_fuel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "incentive_type",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "incentive_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "budget_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("scrap_date", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "db_table": "scrap_it",
            },
        ),
    ]
