# Generated by Django 3.1.6 on 2024-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_auto_20240326_2152"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoElectricRebates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_timestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("create_user", models.CharField(default="SYSTEM", max_length=130)),
                ("update_timestamp", models.DateTimeField(auto_now=True, null=True)),
                ("update_user", models.CharField(max_length=130, null=True)),
                ("approvals", models.CharField(blank=True, max_length=20, null=True)),
                ("date", models.DateField(blank=True, max_length=20, null=True)),
                ("fleet", models.CharField(max_length=20)),
                (
                    "applicant_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "max_incentive_amount_requested",
                    models.IntegerField(blank=True, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "applicant_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("incentive_paid", models.IntegerField(blank=True, null=True)),
                ("total_purchase_price", models.IntegerField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=250, null=True)),
                ("ger_class", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "go_electric_rebates",
            },
        ),
        migrations.DeleteModel(
            name="SpecialityUseVehicleIncentives",
        ),
    ]
