# Generated by Django 3.2.25 on 2024-05-16 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_auto_20240514_1721"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goelectricrebates",
            old_name="ger_class",
            new_name="vehicle_class",
        ),
        migrations.AddField(
            model_name="goelectricrebates",
            name="city",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goelectricrebates",
            name="email",
            field=models.CharField(default="a", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goelectricrebates",
            name="flagged",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="goelectricrebates",
            name="phone",
            field=models.CharField(default="123", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goelectricrebates",
            name="postal_code",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="goelectricrebates",
            name="vin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="applicant_name",
            field=models.CharField(default="a", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="approvals",
            field=models.CharField(default="a", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="category",
            field=models.CharField(default="a", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="incentive_paid",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="manufacturer",
            field=models.CharField(default="a", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="model",
            field=models.CharField(default="a", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="total_purchase_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
