# Generated by Django 3.2.25 on 2024-05-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_auto_20240516_2248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedvinsfile",
            name="chunk_size",
            field=models.IntegerField(default=5000),
        ),
    ]
