# Generated by Django 3.2.25 on 2024-06-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_goelectricrebates_rebate_adjustment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedvinsfile",
            name="chunks_per_run",
        ),
        migrations.AddField(
            model_name="uploadedvinrecord",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedvinrecord",
            name="postal_code",
            field=models.CharField(max_length=7),
        ),
    ]
