# Generated by Django 3.2.25 on 2024-07-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_goelectricrebates_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goelectricrebates",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="goelectricrebates",
            name="total_purchase_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
