# Generated by Django 3.2.25 on 2024-07-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20240712_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcprojecttracking',
            old_name='arc_funding',
            new_name='funds_disbursed',
        ),
        migrations.RenameField(
            model_name='arcprojecttracking',
            old_name='funds_issued',
            new_name='jobs',
        ),
        migrations.RenameField(
            model_name='arcprojecttracking',
            old_name='on_road_off_road',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='arcprojecttracking',
            name='complete_or_termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arcprojecttracking',
            name='economic_region',
            field=models.CharField(default='Across BC', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcprojecttracking',
            name='funds_commited',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcprojecttracking',
            name='remaining_disbursed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arcprojecttracking',
            name='retrofit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='arcprojecttracking',
            name='vehicle_category',
            field=models.CharField(default='A', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='funding_call',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='primary_location',
            field=models.CharField(default='BC', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='project_title',
            field=models.CharField(default='Title', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='proponent',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='publicly_announced',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='reference_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arcprojecttracking',
            name='status',
            field=models.CharField(default='Valid', max_length=250),
            preserve_default=False,
        ),
    ]
