# Generated by Django 3.2.25 on 2024-09-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('funding_call', models.IntegerField(max_length=5)),
                ('project_identifier', models.IntegerField(max_length=5)),
                ('applicant_name', models.CharField(max_length=50)),
                ('rank', models.IntegerField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True, max_length=5, null=True)),
                ('vehicle_deployed', models.CharField(max_length=50)),
                ('vehicle_category', models.CharField(max_length=50)),
                ('drive_type', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('portfolio', models.CharField(max_length=50)),
                ('make_and_model', models.CharField(max_length=50)),
                ('economic_region', models.CharField(max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project_type', models.CharField(max_length=50)),
                ('class_3', models.IntegerField(blank=True, max_length=3, null=True)),
                ('class_4', models.IntegerField(blank=True, max_length=3, null=True)),
                ('class_5', models.IntegerField(blank=True, max_length=3, null=True)),
                ('class_6', models.IntegerField(blank=True, max_length=3, null=True)),
                ('class_7', models.IntegerField(blank=True, max_length=3, null=True)),
                ('class_8', models.IntegerField(blank=True, max_length=3, null=True)),
                ('on_road_total', models.IntegerField(blank=True, max_length=5, null=True)),
                ('off_road', models.IntegerField(blank=True, max_length=5, null=True)),
                ('level_2_charger', models.IntegerField(blank=True, max_length=5, null=True)),
                ('level_3_charger', models.IntegerField(blank=True, max_length=5, null=True)),
                ('high_level_3_charger', models.IntegerField(blank=True, max_length=5, null=True)),
                ('level_charger', models.IntegerField(blank=True, max_length=5, null=True)),
                ('other_charger', models.IntegerField(blank=True, max_length=5, null=True)),
                ('h2_fuelling_station', models.IntegerField(blank=True, max_length=5, null=True)),
                ('charger_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('h2_fuelling_station_description', models.CharField(blank=True, max_length=500, null=True)),
                ('ghg_emission_reduction', models.IntegerField(blank=True, max_length=5, null=True)),
                ('estimated_ghg_emission_reduction', models.IntegerField(blank=True, max_length=5, null=True)),
                ('funding_efficiency', models.IntegerField(blank=True, max_length=5, null=True)),
                ('market_emission_reductions', models.IntegerField(blank=True, max_length=5, null=True)),
                ('cvp_funding_request', models.IntegerField(max_length=10)),
                ('cvp_funding_contribution', models.IntegerField(max_length=10)),
                ('external_funding', models.IntegerField(blank=True, max_length=10, null=True)),
                ('proponent_funding', models.IntegerField(blank=True, max_length=10, null=True)),
                ('project_cost_initial', models.IntegerField(max_length=10)),
                ('project_cost_revised', models.IntegerField(max_length=10)),
                ('funding_source', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('imhzev', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cvp_data',
            },
        ),
    ]
