# Generated by Django 3.2.25 on 2024-09-10 21:43

from django.db import migrations, models

def add_cvp_data_to_datasets(apps, schema_editor):

    Datasets = apps.get_model('api', 'Datasets')

    Datasets.objects.get_or_create(
        create_timestamp="2024-09-10 00:00:00+00",
        create_user="user",
        name="CVP Data"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_cvpdata'),
    ]



    operations = [
        migrations.AlterField(
            model_name='cvpdata',
            name='class_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='class_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='class_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='class_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='class_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='class_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='cvp_funding_contribution',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='cvp_funding_request',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='estimated_ghg_emission_reduction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='external_funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='funding_call',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='funding_efficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='ghg_emission_reduction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='h2_fuelling_station',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='high_level_3_charger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='level_2_charger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='level_3_charger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='level_charger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='market_emission_reductions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='off_road',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='on_road_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='other_charger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='project_cost_initial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='project_cost_revised',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='project_identifier',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='proponent_funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(add_cvp_data_to_datasets),
    ]
