# Generated by Django 3.2.25 on 2024-09-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20240910_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvpdata',
            name='applicant_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='charger_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='drive_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='funding_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='imhzev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='make_and_model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='portfolio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='project_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='vehicle_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='vehicle_deployed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
    ]
