# Generated by Django 3.2.25 on 2024-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20240911_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvpdata',
            name='funding_source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cvpdata',
            name='imhzev',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
