# Generated by Django 3.2.25 on 2024-10-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_addregions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvpdata',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='cvpdata',
            name='road_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvpdata',
            name='use_case',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
