# Generated by Django 3.2.25 on 2024-11-07 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20241031_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('sheet', models.TextField(blank=True, null=True)),
                ('columns', models.TextField(blank=True, null=True)),
                ('formats', models.TextField(blank=True, null=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_requirements', to='api.datasets')),
            ],
            options={
                'db_table': 'file_requirements',
            },
        ),
    ]
