# Generated by Django 3.2.25 on 2025-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_add_datasets_and_file_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('applicant_type', models.CharField(max_length=100)),
                ('application_id', models.CharField(max_length=100, unique=True)),
                ('dealership_name', models.CharField(max_length=100)),
                ('date_submitted', models.DateField()),
                ('payment_dt', models.DateField()),
                ('bc_drivers_license_no', models.CharField(max_length=100, unique=True)),
                ('bc_inc_no', models.CharField(max_length=100, unique=True)),
                ('eligible_rebate_amt', models.IntegerField()),
                ('sale_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('year', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('trim', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_class', models.CharField(blank=True, max_length=50, null=True)),
                ('msrp', models.IntegerField(blank=True, null=True)),
                ('electric_range', models.IntegerField(blank=True, null=True)),
                ('vin_token', models.CharField(blank=True, max_length=9, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('business_corp_name', models.CharField(blank=True, max_length=200, null=True)),
                ('car_share_name', models.CharField(blank=True, max_length=200, null=True)),
                ('non_profit_name', models.CharField(blank=True, max_length=200, null=True)),
                ('municipality_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('lease_term', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ldv_data',
            },
        ),
    ]
