# Generated by Django 3.2.25 on 2025-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_ldvdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldvdata',
            name='bc_drivers_license_no',
            field=models.CharField(max_length=100),
        ),
    ]
