# Generated by Django 3.2.25 on 2025-03-18 18:34

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_ldvdata_bc_drivers_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldvdata',
            name='bc_inc_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ldvdata',
            name='vin',
            field=models.CharField(max_length=17),
        ),
        migrations.RunSQL(
            "INSERT INTO datasets (create_user, update_user, name) VALUES ('SYSTEM', 'SYSTEM', 'LDV Data');"
        ),
    ]
