# Generated by Django 3.2.25 on 2025-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20250318_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldvdata',
            name='bc_drivers_license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ldvdata',
            name='bc_inc_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
