# Generated by Django 3.2.25 on 2025-09-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20250409_2041'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploadedvinrecord',
            name='unique_vin_postal_code',
        ),
        migrations.RenameField(
            model_name='uploadedvinsfile',
            old_name='chunk_size',
            new_name='chunksize',
        ),
        migrations.RemoveField(
            model_name='uploadedvinrecord',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='uploadedvinrecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='uploadedvinrecord',
            name='change',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('removed', 'Removed')], default='created', max_length=64),
        ),
        migrations.AddField(
            model_name='uploadedvinsfile',
            name='chunks_per_iteration',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='uploadedvinrecord',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
