# Generated by Django 3.2.25 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_add_ldv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvinsfile',
            name='icbc',
            field=models.BooleanField(default=True),
        ),
    ]

