# Generated by Django 3.2.25 on 2026-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20260317_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedvinrecord',
            old_name='vinpower_current_decode_successful',
            new_name='vinpower_decode_successful',
        ),
        migrations.RenameField(
            model_name='uploadedvinrecord',
            old_name='vinpower_number_of_current_decode_attempts',
            new_name='vinpower_number_of_decode_attempts',
        ),
        migrations.RenameField(
            model_name='uploadedvinrecord',
            old_name='vpic_current_decode_successful',
            new_name='vpic_decode_successful',
        ),
        migrations.RenameField(
            model_name='uploadedvinrecord',
            old_name='vpic_number_of_current_decode_attempts',
            new_name='vpic_number_of_decode_attempts',
        ),
        migrations.RemoveField(
            model_name='uploadedvinrecord',
            name='change',
        ),
        migrations.RemoveField(
            model_name='uploadedvinrecord',
            name='data',
        ),
        migrations.RemoveField(
            model_name='uploadedvinsfile',
            name='processed',
        ),
        migrations.AddField(
            model_name='uploadedvinsfile',
            name='status',
            field=models.TextField(choices=[('error', 'Error'), ('processing', 'Processing'), ('success', 'Success')], default='processing'),
        ),
        migrations.AlterField(
            model_name='uploadedvinrecord',
            name='vin',
            field=models.TextField(unique=True),
        ),
    ]
