# Generated by Django 6.0.4 on 2026-04-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_auto_20260317_0625"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="icbcregistrationdata",
            name="icbc_upload_date",
        ),
        migrations.RemoveField(
            model_name="icbcregistrationdata",
            name="icbc_vehicle",
        ),
        migrations.AlterUniqueTogether(
            name="icbcvehicle",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="icbcvehicle",
            name="model_year",
        ),
        migrations.DeleteModel(
            name="VINDecodedInformation",
        ),
        migrations.DeleteModel(
            name="IcbcUploadDate",
        ),
        migrations.DeleteModel(
            name="IcbcRegistrationData",
        ),
        migrations.DeleteModel(
            name="IcbcVehicle",
        ),
    ]
