# Generated by Django 3.2.25 on 2026-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20260317_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcbcDuplicateVin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'icbc_duplicate_vin',
            },
        ),
    ]
