# Generated by Django 6.0.4 on 2026-04-19 03:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_remove_icbcregistrationdata_icbc_upload_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IcbcDuplicateVin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.TextField(unique=True)),
            ],
            options={
                "db_table": "icbc_duplicate_vin",
            },
        ),
        migrations.CreateModel(
            name="IcbcVinLookup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.TextField(unique=True)),
            ],
            options={
                "db_table": "icbc_vin_lookup",
            },
        ),
        migrations.RemoveIndex(
            model_name="icbcrecord",
            name="icbc_vin_0f2668_idx",
        ),
        migrations.RemoveField(
            model_name="uploadedvinsfile",
            name="chunks_per_iteration",
        ),
        migrations.RemoveField(
            model_name="uploadedvinsfile",
            name="chunksize",
        ),
        migrations.RemoveField(
            model_name="uploadedvinsfile",
            name="start_index",
        ),
        migrations.AddField(
            model_name="uploadedvinsfile",
            name="byte_offset",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploadedvinsfile",
            name="first_snapshot_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="uploadedvinsfile",
            name="headers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=[]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedvinsfile",
            name="headers_byte_length",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedvinsfile",
            name="last_encountered_vin",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="uploadedvinsfile",
            name="status",
            field=models.TextField(
                choices=[
                    ("NEW", "New"),
                    ("SUCCESS", "Success"),
                    ("PROCESSING", "Processing"),
                    ("ERROR", "Error"),
                    (
                        "SUCCESS_SAVING_FIRST_SNAPSHOT_DATE",
                        "Success Saving First Snapshot Date",
                    ),
                    (
                        "ERROR_SAVING_FIRST_SNAPSHOT_DATE",
                        "Error Saving First Snapshot Date",
                    ),
                    ("SAVING_DUPLICATES_AND_LOOKUPS", "Saving Duplicates And Lookups"),
                    (
                        "SUCCESS_SAVING_DUPLICATES_AND_LOOKUPS",
                        "Success Saving Duplicates And Lookups",
                    ),
                    (
                        "ERROR_SAVING_DUPLICATES_AND_LOOKUPS",
                        "Error Saving Duplicates And Lookups",
                    ),
                    ("TRACKING_REMOVED_RECORDS", "Tracking Removed Records"),
                    (
                        "SUCCESS_TRACKING_REMOVED_RECORDS",
                        "Success Tracking Removed Records",
                    ),
                    (
                        "ERROR_TRACKING_REMOVED_RECORDS",
                        "Error Tracking Removed Records",
                    ),
                    (
                        "TRACKING_CREATED_AND_MODIFIED_RECORDS",
                        "Tracking Created And Modified Records",
                    ),
                    (
                        "ERROR_TRACKING_CREATED_AND_MODIFIED_RECORDS",
                        "Error Tracking Created And Modified Records",
                    ),
                ],
                default="NEW",
            ),
        ),
        migrations.AddIndex(
            model_name="icbcrecord",
            index=models.Index(
                fields=["vin", "-create_timestamp"], name="icbc_vin_dc3b83_idx"
            ),
        ),
    ]
