# Generated by Django 6.0.4 on 2026-04-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_icbcduplicatevin_icbcvinlookup_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="icbcrecord",
            name="icbc_vin_dc3b83_idx",
        ),
        migrations.AddIndex(
            model_name="icbcrecord",
            index=models.Index(
                fields=["vin", "-snapshot_date"], name="icbc_vin_efd0d6_idx"
            ),
        ),
    ]
