# Generated by Django 6.0.4 on 2026-07-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_remove_icbcrecord_icbc_vin_dc3b83_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="icbcrecord",
            name="icbc_vin_efd0d6_idx",
        ),
        migrations.AlterField(
            model_name="uploadedvinsfile",
            name="status",
            field=models.TextField(
                choices=[
                    ("NEW", "New"),
                    ("SUCCESS_WRITING_FILE_TO_DISK", "Success Writing File To Disk"),
                    ("ERROR_WRITING_FILE_TO_DISK", "Error Writing File To Disk"),
                    ("SUCCESS", "Success"),
                    ("PROCESSING", "Processing"),
                    ("ERROR", "Error"),
                    (
                        "SUCCESS_SAVING_FIRST_SNAPSHOT_DATE",
                        "Success Saving First Snapshot Date",
                    ),
                    (
                        "ERROR_SAVING_FIRST_SNAPSHOT_DATE",
                        "Error Saving First Snapshot Date",
                    ),
                    ("SAVING_DUPLICATES_AND_LOOKUPS", "Saving Duplicates And Lookups"),
                    (
                        "SUCCESS_SAVING_DUPLICATES_AND_LOOKUPS",
                        "Success Saving Duplicates And Lookups",
                    ),
                    (
                        "ERROR_SAVING_DUPLICATES_AND_LOOKUPS",
                        "Error Saving Duplicates And Lookups",
                    ),
                    ("TRACKING_REMOVED_RECORDS", "Tracking Removed Records"),
                    (
                        "SUCCESS_TRACKING_REMOVED_RECORDS",
                        "Success Tracking Removed Records",
                    ),
                    (
                        "ERROR_TRACKING_REMOVED_RECORDS",
                        "Error Tracking Removed Records",
                    ),
                    (
                        "TRACKING_CREATED_AND_MODIFIED_RECORDS",
                        "Tracking Created And Modified Records",
                    ),
                    (
                        "ERROR_TRACKING_CREATED_AND_MODIFIED_RECORDS",
                        "Error Tracking Created And Modified Records",
                    ),
                ],
                default="NEW",
            ),
        ),
        migrations.AddIndex(
            model_name="icbcrecord",
            index=models.Index(
                fields=["vin", "-change_date"], name="icbc_vin_14f28f_idx"
            ),
        ),
    ]
