FROM artifacts.developer.gov.bc.ca/docker-remote/eclipse-temurin:17-jdk-jammy AS builder

ARG ARTIFACTORY_URL
ARG ARTIFACTORY_USER
ARG ARTIFACTORY_PASSWORD

WORKDIR /app
ENV MAVEN_CONFIG=/tmp/.m2

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN chmod +x mvnw

RUN mkdir -p /app/libs
RUN curl -fsSL -u "${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD}" \
    -o /app/libs/vp4jo_bttm_msrp_gvw_50011.jar \
    "${ARTIFACTORY_URL}"

RUN ./mvnw dependency:resolve

COPY src ./src

FROM artifacts.developer.gov.bc.ca/docker-remote/eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY --from=builder /tmp/.m2 /tmp/.m2
COPY --from=builder /app /app

RUN chgrp -R 0 /app /tmp/.m2 && \
    chmod -R g=u /app /tmp/.m2

EXPOSE 8080

USER 1001

CMD ["./mvnw", "-Denvironment=production", "spring-boot:run"]
