apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: cthub-frontend-tekton
  annotations:
    description: Defines how to deploy the frontend application
  creationTimestamp: null
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    name: cthub-frontend-tekton
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: cthub-frontend-tekton
    spec:
      containers:
        - name: frontend
          env:
            - name: API_BASE
              value: "https://cthub-backend-tekton.apps.silver.devops.gov.bc.ca"
            - name: ENABLE_KEYCLOAK
              value: "true"
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cthub-keycloak
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: cthub-keycloak
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: cthub-keycloak
                  key: KEYCLOAK_URL
          image:
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 50
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 3
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 5002
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - frontend
        from:
          kind: ImageStreamTag
          name: image-registry.openshift-image-registry.svc:5000/30b186-tools/cthub-frontend:frontendtekton
        lastTriggeredImage:
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
