kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nodejs-oc-bc
  namespace: 30b186-tools
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      namespace: 30b186-tools
      name: 'nodejs-oc:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      noCache: true
      forcePull: true
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/cthub.git'
      ref: prbased-teckton-0.2.0
    contextDir: .tekton/prbased/nodejs-oc
  runPolicy: Serial

