apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: ARTIFACTORY_URL
  description: 
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: cthub-artifactory
  stringData:
    ARTIFACTORY_URL: ${ARTIFACTORY_URL}

