FROM registry.fedoraproject.org/f35/python3:3.10.0

# Add application sources with correct permissions for OpenShift
USER 0
WORKDIR /opt/app-root/src
ADD . .
RUN chown -R 1001:0 ./
USER 1001

# # Install the dependencies
RUN pip install -U "pip>=19.3.1" && \
    pip install -r requirements.txt 
RUN ls -l \
    && python -V

# # Run the application
CMD python manage.py runserver 0.0.0.0:8080