apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-cthub
  namespace: 30b186-tools
spec:
  params:
    - description: the git repo url, https://github.com/bcgov/cthub.git
      name: repo-url
      type: string
    - description: the git branch name, tekton-0.1.0
      name: branch
      type: string
    - description: where the frontend image push to, image-registry.openshift-image-registry.svc:5000/30b186-tools/cthub-frontend:frontendtekton
      name: frontend-image
      type: string
    - description: where the backend image push to, image-registry.openshift-image-registry.svc:5000/30b186-tools/cthub-backend:backendtekton
      name: backend-image
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
    - name: show-dir
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: show-dir
      workspaces:
        - name: source
          workspace: shared-data
    - name: build-backend
      params:
        - name: PATH_CONTEXT
          value: /workspace/source/django
        - name: IMAGE
          value: $(params.backend-image)
      runAfter:
        - show-dir
      taskRef:
        kind: ClusterTask
        name: s2i-python
      workspaces:
        - name: source
          workspace: shared-data          
  workspaces:
    - description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.      
      name: shared-data
