apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-cthub
  namespace: 30b186-tools
spec:
  params:
    - description: the git repo url
      name: repo-url
      type: string
    - description: the git branch name
      name: branch
      type: string
    - description: where the frontend image push to
      name: frontend-image
      type: string
    - description: where the backend image push to
      name: backend-image
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
    - name: show-dir
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: show-dir
      workspaces:
        - name: source
          workspace: shared-data
    # - name: build-backend
    #   params:
    #     - name: PATH_CONTEXT
    #       value: /workspace/source/django
    #     - name: IMAGE
    #       value: $(params.backend-image)
    #   runAfter:
    #     - show-dir
    #   taskRef:
    #     kind: ClusterTask
    #     name: s2i-python
    #   workspaces:
    #     - name: source
    #       workspace: shared-data          
    # - name: build-frontend
    #   params:
    #     - name: PATH_CONTEXT
    #       value: /workspace/source/react
    #     - name: IMAGE
    #       value: $(params.frontend-image)
    #   runAfter:
    #     - show-dir
    #   taskRef:
    #     kind: ClusterTask
    #     name: s2i-nodejs
    #   workspaces:
    #     - name: source
    #       workspace: shared-data          
  workspaces:
    - description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.      
      name: shared-data
