apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cthub-trigger-tt
spec:
  params:
    - description: the git repo url
      name: repo-url
    - description: the git branch name
      name: branch
    - description: the git repo url
      name: repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-cthub-$(tt.params.repo-name)-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: build-cthub
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: branch
            value: $(tt.params.branch)
          - name: frontend-image
            value: >-
              image-registry.openshift-image-registry.svc:5000/30b186-tools/cthub-frontend:frontendtekton
          - name: backend-image
            value: >-
              image-registry.openshift-image-registry.svc:5000/30b186-tools/cthub-backend:backendtekton      
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi