apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-s2i-nodejs-pr
spec:
  pipelineRef:
    name: test-s2i-nodejs
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi