apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Metabase secret
  name: cthub-metabase-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: cthub
    name: cthub-metabase
  stringData:
    mb-db-dbname: ${MB_DB_NAME}
    mb-db-user: ${MB_DB_USER}
    mb-db-password: ${MB_DB_PASSWORD}
parameters:
- description: The database name
  displayName: Database Name
  name: MB_DB_NAME
  value: metabase
- description: Username 
  displayName: Username
  name: MB_DB_USER
  from: metabase[a-z]{8}
  generate: expression
- description: Password 
  displayName: Passsword
  name: MB_DB_PASSWORD
  generate: expression
  from: '[a-zA-Z0-9]{8}'
