apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: frontend-bc
  labels:
    testlabel: kuan
parameters:
  - name: NAME
    displayName: null
    description: 'the module name entered when run yo bcdk:pipeline, which is cthub'
    required: true
  - name: SUFFIX
    displayName: null
    description: sample is -pr-0
    required: true
  - name: VERSION
    displayName: null
    description: image tag name for output
    required: true
  - name: GIT_URL
    displayName: null
    description: cthub repo
    required: true
  - name: GIT_REF
    displayName: null
    description: cthub branch name of the pr
    required: true
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: cthub-frontend-build-80
      namespace: 30b186-tools
      labels:
        kuanapp: cthub-test-label
        github-repo: cthub
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: 'cthub-frontend:build-1.0.0-80'
      resources:
        limits:
          cpu: '2'
          memory: 2G
        requests:
          cpu: 500m
          memory: 200M
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      source:
        type: Git
        git:
          ref: "refs/pull/80/head"
          uri: "https://github.com/bcgov/cthub.git"
        contextDir: react
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: 30b186-tools
            name: 'nodejs-14:1-46.1634035772'
          env:
            - name: ARTIFACTORY_USER
              valueFrom:
                secretKeyRef:
                  name: artifacts-default-idxprm
                  key: username
            - name: ARTIFACTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: artifacts-default-idxprm
                  key: password
          forcePull: true
      postCommit: {}
      runPolicy: Serial
