apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bcdk-build
  namespace: 30b186-tools
spec:
  params:
    - description: the pull-request number
      name: pull-request
      type: string
  steps:
    - image: 'image-registry.openshift-image-registry.svc:5000/30b186-tools/nodejs-oc:latest'
      name: build-pull-request
      resources: {}
      script: |
        #!/usr/bin/env bash
        cd /source
        cp -r .pipeline pipeline
        cd pipeline
        pwd
        ls -la
        echo "$(inputs.params.pull-request)"
        ./npmw ci
        ./npmw run build -- --pr=$(inputs.params.pull-request) --env=build
  workspaces:
    - name: source
      description: the folder where the project was checked out
      mountPath: /source
      readOnly: false
