FROM artifacts.developer.gov.bc.ca/docker-remote/postgrest/postgrest:v14.2

# RUN apt-get -y update \
#     && apt-get -y install curl

# RUN mkdir /var/run/postgresql \
#     && chgrp -R root /var/run/postgresql \
#     && chmod -R g+w /var/run/postgresql

USER 1001