## For each release, the value of workflow name, branches and VERSION need to be adjusted accordingly

name: CTHUB 0.2.0 Task Queue Dev CI

on:
  push:
    branches: [ task-queue-0.2.0 ]
  workflow_dispatch:

env:
  VERSION: 0.2.0
  GIT_URL: https://github.com/bcgov/cthub.git 
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  DEV_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

jobs:

  set-pre-release:
    name: Calculate pre-release number
    runs-on: ubuntu-latest
  
    outputs:
      output1: ${{ steps.set-pre-release.outputs.PRE_RELEASE }}
    
    steps:
      - id: set-pre-release
        run: echo "PRE_RELEASE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

  build:

    name: Build CTHUB task queue
    runs-on: ubuntu-latest
    needs: set-pre-release
    timeout-minutes: 60

    env:
      PRE_RELEASE: ${{ needs.set-pre-release.outputs.output1 }}

    steps:

      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TOOLS_NAMESPACE }}

      - name: Build CTHUB task queue
        run: |
          cd openshift/templates/task-queue
          oc process -f ./task-queue-bc.yaml NAME=cthub SUFFIX=-${{ env.VERSION }}-${{ env.PRE_RELEASE }} VERSION=${{ env.VERSION }}-${{ env.PRE_RELEASE }} GIT_URL=${{ env.GIT_URL }} GIT_REF=release-${{ env.VERSION }} | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
          sleep 5s
          oc -n ${{ env.TOOLS_NAMESPACE }} wait --for=condition=Complete --timeout=900s build/cthub-task-queue-${{ env.VERSION }}-${{ env.PRE_RELEASE }}-1
          oc tag ${{ env.TOOLS_NAMESPACE }}/cthub-task-queue:${{ env.VERSION }}-${{ env.PRE_RELEASE }} ${{ env.DEV_NAMESPACE }}/cthub-task-queue:${{ env.VERSION }}-${{ env.PRE_RELEASE }}


  # deploy:

  #   name: Deploy CTHUB task queue on Dev
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   needs: [set-pre-release, build]

  #   env:
  #     PRE_RELEASE: ${{ needs.set-pre-release.outputs.output1 }}

  #   steps:
      
  #     - name: Checkout Manifest repository
  #       uses: actions/checkout@v4.1.1
  #       with:
  #         repository: bcgov-c/tenant-gitops-30b186
  #         ref: main
  #         ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
      
  #     - name: Update task-queue tag
  #       uses: mikefarah/yq@v4.40.5
  #       with:
  #           cmd: yq -i '.task-queue.image.tag = "${{ env.VERSION }}-${{ env.PRE_RELEASE }}"' cthub/values-dev.yaml

  #     - name: GitHub Commit & Push
  #       run: |
  #         git config --global user.email "actions@github.com"
  #         git config --global user.name "GitHub Actions"
  #         git add cthub/values-dev.yaml
  #         git commit -m "Update the image tag to ${{ env.VERSION }}-${{ env.PRE_RELEASE }} on Dev"
  #         git push
      