name: CTHUB prettier test

on:
  push:
    branches: [ prettier-0.3.0 ]
  workflow_dispatch:

jobs:
  
  test-prettier:

    name: prettier
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}

      - name: pwd
        run: |
          pwd
          ls -l

      - name: Run python black code formatter
        uses: DataDog/action-py-black-formatter@v2.5
        with:
          fail_on_error: "false"
      