apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: superset-dc
parameters:
  - name: ENV_NAME
    value: 
    required: true
  - name: SUFFIX
    displayName: null
    description: sample is -dev-97    
  - name: CPU_REQUEST
    value: 50M
    displayName: Requested CPU
    description: Requested CPU
    required: true    
  - name: CPU_LIMIT
    value: 200M
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    value: 50M
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    value: 200M
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: REPLICAS
    description: |
      The number of replicas to use.
    displayName: REPLICAS
    value: "1"    
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cthub-superset
    labels:
      app: cthub-superset
      service: cthub-superset
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: cthub-superset
    name: cthub-superset
  spec:
    ports:
    - name: superset-web
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: cthub-superset
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: cthub-superset
    name: cthub-superset
  spec:
    host: superset-${ENV_NAME}.apps.silver.devops.gov.bc.ca
    path: /
    port:
      targetPort: superset-web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: cthub-superset
      weight: 100
    wildcardPolicy: None
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: cthub-superset
    name: cthub-superset
  spec:
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 10
    selector:
      app: cthub-superset
      deploymentconfig: cthub-superset
    strategy:
      activeDeadlineSeconds: 600
      recreateParams:
        timeoutSeconds: 300
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: cthub-superset
          deploymentconfig: cthub-superset
      spec:
        containers:
        - name: cthub-superset
          image:
          imagePullPolicy: Always
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: cthub-superset
        serviceAccountName: cthub-superset
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cthub-superset
        from:
          kind: ImageStreamTag
          name: superset:v1.0
          namespace: 30b186-tools
        lastTriggeredImage: 
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
